# Ensures packages build correctly
name: Build Packages

on:
  push:

jobs:
  build:
    name: Build Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Enable Corepack
        run: corepack enable
      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'yarn'

      # Build is triggered in prepare script
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
