# Ensures packages build correctly
name: Build Packages

on:
  push:

jobs:
  build:
    name: Build Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Setup Yarn
        run: |
          npm install -g yarn
          echo "Yarn version: $(yarn -v)"

      # Build is triggered in prepare script
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
