# Action to publish packages under the `next` tag for testing
# Packages are versioned as `0.0.0-{tag}-DATETIMESTAMP`
name: Packages Deploy

on: workflow_dispatch

jobs:
  publish:
    name: Publish Dev Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Yarn
        run: |
          npm install -g yarn
          echo "Yarn version: $(yarn -v)"
          echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" >> ~/.npmrc

        # This also builds the package as part of the post install
      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Development Version
        run: |
          node ./scripts/dev-package-pre-version.js
          yarn changeset version --no-git-tag --snapshot dev
          yarn changeset publish --tag dev
